import type { Metadata } from "next";

import "./globals.css";
import {Quicksand } from "next/font/google";
// Poppins Medium
const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
<body
        className={`${quicksand.variable} antialiased`}
      >
          {children}
      </body>
    </html>
  );
}
